version: '3.6'

services:
    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: appdb
    hasura:
        image: hasura/graphql-engine:v1.3.3
        ports:
            - "8080:8080"
        restart: always
        depends_on:
            - "postgres"
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:A77Jy+u4tJs2iPnh+UwVIg@postgres:5432/appdb
            ## enable the console served by server
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
            ## enable debugging mode. It is recommended to disable this in production
            HASURA_GRAPHQL_DEV_MODE: "true"
            # HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
            ## uncomment next line to set an admin secret
            HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
    fusionauth:
        image: fusionauth/fusionauth-app:latest
        depends_on:
            - postgres
        environment:
            DATABASE_URL: jdbc:postgresql://postgres:5432/fusionauth
            DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
            DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}

            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
 
            FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
            FUSIONAUTH_APP_RUNTIME_MODE: development
            FUSIONAUTH_APP_URL: http://localhost:9011
            SEARCH_TYPE: database


        
        restart: unless-stopped
        ports:
            - 9011:9011
        volumes:
            - fa_config:/usr/local/fusionauth/config
volumes:
    postgres_data:
    fa_config: